osx_image: xcode8
language: objective-c

install:
  - bundle install --without=documentation
  - cd Example && bundle exec pod install && cd $TRAVIS_BUILD_DIR

script:
  - xcodebuild test -workspace Example/TBStateMachine.xcworkspace -scheme TBStateMachineTests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO